# Install postgresql
- name: "Add PostgreSQL 12 GPG key"
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: "Add PostgreSQL 12 repository"
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main"
    state: present

- name: "Install PostgreSQL 12"
  apt:
    name:
      - postgresql-12
      - postgresql-client-12
      - python3-psycopg2
    state: present

# Start postgresql
- name: Ensure PostgreSQL is running
  systemd:
    name: postgresql
    state: started
    enabled: true

# Configure postgresql
- name: "Upload pg_hba.conf"
  copy:
    src: ../files/pg_hba.conf
    dest: /etc/postgresql/12/main/pg_hba.conf
  register: pg_hba_conf

- name: "Upload postgresql.conf"
  template:
    src: ../files/postgresql.conf
    dest: /etc/postgresql/12/main/postgresql.conf
  register: postgresql_conf

# Restart postgresql
- name: Restart PostgreSQL if configuration changed
  systemd:
    name: postgresql
    state: restarted
    enabled: true
    daemon_reload: true
  when: pg_hba_conf.changed or postgresql_conf.changed

# Create database
- name: "Create database"
  postgresql_db:
    login_unix_socket: "/var/run/postgresql"
    name: "{{ postgresql_db_name }}"
    state: present

# Create user
- name: Create user
  postgresql_user:
    login_unix_socket: "/var/run/postgresql"
    db: "{{ postgresql_db_name }}"
    name: "{{ postgresql_user_name }}"
    password: "{{ postgresql_user_password }}"
    state: present

# Set limited permissions
##TODO: Set limited permissions

# Create database scheme
- name: "Upload database scheme"
  copy:
    src: ../files/schema.sql
    dest: /tmp/schema.sql

# This is a non-idempotent task, because it is not possible to check if the
# database scheme is already created. Therefore, we use the "changed_when"
# statement to ignore the result of this task.
- name: "Ensure database scheme"
  community.postgresql.postgresql_script:
    login_user: "{{ postgresql_user_name }}"
    login_password: "{{ postgresql_user_password }}"
    login_host: "127.0.0.1"
    db: "{{ postgresql_db_name }}"
    path: /tmp/schema.sql
  changed_when: false
