- name: Ensure Redis is present
  apt:
    name: redis-server
    state: latest

- name: Ensure Redis is started
  systemd:
    name: redis-server
    state: started
    enabled: true

- name: Ensure Redis Configuration
  template:
    src: ../files/redis.conf
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: 0644
  register: redis_conf

- name: Ensure Redis is restarted
  systemd:
    name: redis-server
    state: restarted
    enabled: true
    daemon_reload: true
  when: redis_conf.changed
