- name: Install Redis
  hosts: redis

  vars_files:
    - group_vars/all.yml
  become: yes

  tasks:
    - name: Ensure Redis is present
      apt:
        name: redis-server
        state: latest

    - name: Ensure Redis is started
      service:
        name: redis-server
        state: started
        enabled: yes

    - name: Ensure Redis Configuration
      template:
        src: ../files/redis.conf
        dest: /etc/redis/redis.conf
        owner: root
        group: root
        mode: 0644
      notify: Redis Restart
