---
- name: Setup all
  hosts: all
  become: true
  roles:
    - base

- name: Setup redis
  hosts: redis
  become: true
  vars_files:
    - group_vars/all.yml
  roles:
    - redis

- name: Setup postgres
  hosts: postgres
  become: true
  vars_files:
    - group_vars/all.yml
  roles:
    - postgresql

- name: Setup poll
  hosts: poll
  become: true
  vars_files:
    - group_vars/all.yml
  roles:
    - poll

- name: Setup result
  hosts: result
  become: true
  vars_files:
    - group_vars/all.yml
  roles:
    - result

- name: Setup worker
  hosts: worker
  become: true
  vars_files:
    - group_vars/all.yml
  roles:
    - worker
