- name: "Upload poll service"
  template:
    src: "../files/poll.service"
    dest: "/etc/systemd/system/poll.service"
    mode: 0644
  notify: Poll restart # This handler will be run after the role is executed

- name: "Upload and extract poll app"
  unarchive:
    src: "../../../poll.tar"
    dest: "/tmp/"
    mode: 0755
  notify: Poll restart

- name: "Install dependencies"
  pip:
    requirements: "/tmp/poll/requirements.txt"
    state: latest
  notify: Poll restart

- name: "Ensure service is started"
  systemd:
    name: poll
    state: started
    enabled: true
