- name: "Upload poll service"
  become: true
  copy:
    src: "../files/poll.service"
    dest: "/etc/systemd/system/poll.service"
    mode: 0644
  notify: Poll restart

- name: "Upload and extract poll app"
  unarchive:
    src: "../../../poll.tar"
    dest: "~"
    mode: 0755
  notify: Poll restart

- name: "Install dependencies"
  pip:
    requirements: "~/poll/requirements.txt"
  notify: Poll restart

- name: Create poll user
  become: true
  user:
    name: poll
    shell: /bin/bash
    state: present

- name: Give access to poll user
  become: true
  file:
    path: "~/poll"
    owner: poll
    group: poll
    state: directory
    mode: 0755

- name: "Ensure service is started"
  become: true
  service:
    name: poll
    state: started
    enabled: yes
